# Generated by Django 4.2 on 2023-04-30 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.CharField(default=7388006830, max_length=12)),
                ('college_name', models.CharField(default='Dnyan Ganga Degree College', max_length=100)),
                ('college_address', models.TextField()),
                ('college_contact', models.IntegerField(verbose_name=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=10)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_address', models.TextField()),
                ('teacher_contact', models.IntegerField(verbose_name=10)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.college')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=10)),
                ('std_name', models.CharField(max_length=100)),
                ('std_address', models.TextField()),
                ('std_contact', models.IntegerField(verbose_name=10)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.college')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_std', models.CharField(default='BSC-IT', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('action', models.BooleanField(default=False)),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.college')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.student')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.teacher')),
            ],
        ),
    ]
